---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# eeaemisje

<!-- badges: start -->
<!-- badges: end -->

Celem pakietu `eeaemisje` jest obliczanie emisji na podstawie danych z EEA. Aby ulatwic prace z pakietem stworzona zostala winieta i system pomocy, ponizej szczególy. 


# Instalacja (szybka)

```{r setup, eval=FALSE}
# Potrzebujesz devtools ?
if (!require(devtools)) {install.packages("devtools"); require(devtools)}

# Instalujesz i wczytujesz
install_git("https://github.com/rajder007/eeaemisje")
library(eeaemisje)
```


Teraz mozesz korzystac z systemu pomocy.

```{r, eval=F}
?"eeaemisje"
?"eea_szaco_emisji"
?"eea_plot"
```


# Instalacja wraz z winietą (wolna)

```{r, eval=F}
# Potrzebujesz devtools ?
if (!require(devtools)) {install.packages("devtools"); require(devtools)}

# Instalujesz i wczytujesz
install_git("https://github.com/rajder007/eeaemisje", force = T, build_vignettes = T)
library(eeaemisje)
```

Teraz mozesz korzystac z rozbudowanego systemu pomocy.

```{r, eval=FALSE}
# Podgląd winiety w przeglądarce
browseVignettes("eeaemisje")

# przejrzyj w oknie pomocy
vignette("eeaemisje")

# wyswietli tylko kod
edit(vignette("eeaemisje"))
```
